// src/components/initialMembers.ts
import type { Member } from "./types";

export const initialMembers: Member[] = [
  {
    id: 1,
    prefix: "นางสาว",
    firstName: "กมนทรรศน์",
    lastName: "กิตติสุนทรสกุล",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new/3540100539076_3.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคประชาชน",
  },
  {
    id: 2,
    prefix: "นาย",
    firstName: "กมลศักดิ์",
    lastName: "ลีวาเมาะ",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/8476b175938b37a3e03e25c0bd1d4b39.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคประชาชาติ",
  },
  {
    id: 3,
    prefix: "นาย",
    firstName: "กรวีร์",
    lastName: "ปริศนานันทกุล",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/367fed0d5e472475b00d12b7f5c9fe01.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคภูมิใจไทย",
  },
  {
    id: 4,
    prefix: "นาย",
    firstName: "กรวีร์",
    lastName: "สาราคำ",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/cb79c00a820a3b0b0549e370d9010d56.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคเพื่อไทย",
  },
  {
    id: 5,
    prefix: "นาย",
    firstName: "กระแสร์",
    lastName: "ตระกูลพรพงศ์",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/43dd23fa8fb668cf50a86af70fc84b00.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคพลังประชารัฐ",
  },
  {
    id: 6,
    prefix: "นาย",
    firstName: "กรุณพล",
    lastName: "เทียนสุวรรณ",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/1cb4ee29bf8955ced230ca9d676cd14a.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคประชาชน",
  },
  {
    id: 7,
    prefix: "นาย",
    firstName: "กฤช",
    lastName: "ศิลปชัย",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/babcec9cd6fb7ffc35bc615d592c9b51.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคประชาชน",
  },
  {
    id: 8,
    prefix: "นาย",
    firstName: "กฤดิทัช",
    lastName: "แสงธนโยธิน",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/f9aa2ac413db397d24adcd7cb6377e6e.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคกล้าธรรม",
  },
  {
    id: 9,
    prefix: "นางสาว",
    firstName: "กฤษฎิ์",
    lastName: "ชีวะธรรมานนท์",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/3f94d4714f4291ded8703c217361ac6e.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคประชาชน",
  },
  {
    id: 10,
    prefix: "นาย",
    firstName: "กฤษฐ์หิรัญ",
    lastName: "เลิศอุฤทธิ์ภักดี",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/d692c56ed38a1c359a4759b3f5d60f63.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคประชาชน",
  },
  {
    id: 11,
    prefix: "นางสาว",
    firstName: "กฤษณา",
    lastName: "สีหลักษณ์",
    photoUrl: "https://hris.parliament.go.th/manage/fileupload/pic_new_public/6ca128c381fc539c8920cd160751dcd8.png",
    workHistory: "",
    achievements: "",
    ministerialPosition: "",
    ministry: "",
    politicalParty: "พรรคเพื่อไทย",
  },
];
